# Generated by Django 4.2.11 on 2026-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainevent',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domainevent',
            name='module',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='domainevent',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
