# Generated by Django 4.2.28 on 2026-02-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finnovaapp', '0002_organization_organizationmembership_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='finnovaapp.organization'),
        ),
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finnovaapp.organization'),
        ),
        migrations.AddField(
            model_name='income',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finnovaapp.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'organization', 'is_primary')},
        ),
    ]
