# Generated by Django 4.2.16 on 2026-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_payment_intent_idempotency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('organization__isnull', False)), fields=('user', 'organization'), name='uniq_primary_finance_account_per_org'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('organization__isnull', True)), fields=('user',), name='uniq_primary_finance_account_personal'),
        ),
    ]
