# Generated by Django 4.2.28 on 2026-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0002_organization_organizationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='segment',
            field=models.CharField(blank=True, choices=[('AGENCY', 'Agency / Service SME'), ('CA_FIRM', 'CA / Bookkeeping Firm'), ('CLINIC', 'Clinic / Healthcare Center'), ('COACHING', 'Coaching Institute')], max_length=20, null=True),
        ),
    ]
