# Generated by Django 4.2.11 on 2026-02-16 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0003_organization_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_required', models.BooleanField(default=True)),
                ('max_autopay_amount', models.DecimalField(decimal_places=2, default=25000, max_digits=12)),
                ('transfer_approval_threshold', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='finnovaapp.organization')),
            ],
        ),
    ]
