# Generated by Django 4.2.28 on 2026-02-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0003_organization_segment'),
        ('payments_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='finnovaapp.organization'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='finnovaapp.organization'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='finnovaapp.organization'),
        ),
    ]
