# Generated by Django 4.2.28 on 2026-02-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0003_organization_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_core', '0002_paymentaccount_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upi_id', models.CharField(max_length=120)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upi_ids', to='finnovaapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'upi_id', 'organization')},
            },
        ),
    ]
