# Generated by Django 4.2.28 on 2026-02-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0003_organization_segment'),
        ('payments_core', '0003_upiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_tokens', to='finnovaapp.organization'),
        ),
    ]
