# Generated by Django 5.2.10 on 2026-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_core', '0004_cardtoken_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('AUTO', 'Auto Payment'), ('REFUND', 'Refund'), ('TOPUP', 'Top-up'), ('DEPOSIT', 'Deposit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('DISPUTED', 'Disputed'), ('CHARGEBACK', 'Chargeback')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('AUTO', 'Auto Payment'), ('REFUND', 'Refund'), ('TOPUP', 'Top-up'), ('DEPOSIT', 'Deposit')], default='CARD', max_length=20),
        ),
    ]
