# Generated by Django 4.2.16 on 2026-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_core', '0005_alter_paymentintent_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('organization__isnull', False)), fields=('user', 'organization'), name='uniq_primary_payment_account_per_org'),
        ),
        migrations.AddConstraint(
            model_name='paymentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('organization__isnull', True)), fields=('user',), name='uniq_primary_payment_account_personal'),
        ),
    ]
