# Generated by Django 4.2.28 on 2026-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_core', '0006_alter_paymentaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Idempotency key for safe retries', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['organization', 'idempotency_key'], name='payments_co_organiz_2ffcf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('organization', 'idempotency_key'), name='uniq_payment_intent_idempotency_per_org'),
        ),
    ]
