# Generated by Django 5.2.10 on 2026-02-10 16:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finnova_autopilot', '0001_initial'),
        ('payments_core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.TextField(blank=True, null=True)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User Action'), ('API', 'API Call'), ('PAYMENT', 'Payment System'), ('FINANCE', 'Finance Module'), ('AUTOPILOT', 'Autopilot'), ('AI', 'AI System'), ('SECURITY', 'Security System'), ('ADMIN', 'Administrator')], default='SYSTEM', max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction'), ('SETTING', 'Setting Change'), ('SECURITY', 'Security Event'), ('ERROR', 'Error'), ('SYSTEM', 'System Event')], default='READ', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='audit.auditlog')),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finnova_autopilot.alert')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_core.paymentintent')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_core.paymenttransaction')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('changed_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('change_source', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail', to='audit.auditlog')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compliance_type', models.CharField(choices=[('KYC', 'Know Your Customer'), ('AML', 'Anti-Money Laundering'), ('GDPR', 'General Data Protection Regulation'), ('PCIDSS', 'PCI Data Security Standard'), ('SOX', 'Sarbanes-Oxley'), ('HIPAA', 'Health Insurance Portability'), ('FATCA', 'Foreign Account Tax Compliance'), ('LOCAL', 'Local Regulations'), ('INTERNAL', 'Internal Policies')], default='KYC', max_length=20)),
                ('requirement', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(default='USER', max_length=50)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('FAILED', 'Failed'), ('EXEMPT', 'Exempt')], default='PENDING', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('audit_trail', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_compliance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'compliance_type'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOGIN', 'Login Alert'), ('FRAUD', 'Fraud Detection'), ('SUSPICIOUS', 'Suspicious Activity'), ('UNAUTHORIZED', 'Unauthorized Access'), ('DATA_BREACH', 'Data Breach'), ('MALWARE', 'Malware Detection'), ('PHISHING', 'Phishing Attempt'), ('BRUTE_FORCE', 'Brute Force Attack'), ('UNUSUAL', 'Unusual Behavior'), ('COMPLIANCE', 'Compliance Violation')], default='SUSPICIOUS', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('investigation_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_action', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_logs', models.ManyToManyField(blank=True, related_name='security_alerts', to='audit.auditlog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='SystemControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('autopilot_enabled', models.BooleanField(default=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('payment_processing_enabled', models.BooleanField(default=True)),
                ('new_registrations_enabled', models.BooleanField(default=True)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('two_factor_required', models.BooleanField(default=False)),
                ('max_daily_transactions', models.PositiveIntegerField(default=50)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
                ('max_monthly_spending', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('kyc_required', models.BooleanField(default=True)),
                ('aml_enabled', models.BooleanField(default=True)),
                ('data_retention_days', models.PositiveIntegerField(default=365)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_end', models.DateTimeField(blank=True, null=True)),
                ('emergency_mode', models.BooleanField(default=False)),
                ('emergency_message', models.TextField(blank=True, null=True)),
                ('current_version', models.CharField(default='1.0.0', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Control',
                'verbose_name_plural': 'System Controls',
            },
        ),
        migrations.CreateModel(
            name='UserRiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('FRAUD', 'Fraud Risk'), ('MONEY_LAUNDERING', 'Money Laundering Risk'), ('CREDIT', 'Credit Risk'), ('OPERATIONAL', 'Operational Risk'), ('COMPLIANCE', 'Compliance Risk'), ('BEHAVIORAL', 'Behavioral Risk'), ('SECURITY', 'Security Risk'), ('REPUTATIONAL', 'Reputational Risk')], default='BEHAVIORAL', max_length=20)),
                ('description', models.TextField()),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_risks', to=settings.AUTH_USER_MODEL)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_risks', to=settings.AUTH_USER_MODEL)),
                ('related_alerts', models.ManyToManyField(blank=True, to='audit.securityalert')),
                ('related_transactions', models.ManyToManyField(blank=True, to='payments_core.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_user', 'created_at'], name='audit_audit_target__514ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['correlation_id'], name='audit_audit_correla_69684b_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['entity_type', 'entity_id', 'changed_at'], name='audit_audit_entity__d1561f_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['changed_by', 'changed_at'], name='audit_audit_changed_f06261_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancerecord',
            index=models.Index(fields=['user', 'compliance_type', 'status'], name='audit_compl_user_id_2d9379_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancerecord',
            index=models.Index(fields=['due_date', 'status'], name='audit_compl_due_dat_466578_idx'),
        ),
    ]
