# Generated by Django 5.2.10 on 2026-02-12 20:13

import audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, decoder=audit.models.UUIDAwareJSONDecoder, default=dict),
        ),
    ]
