# Generated by Django 4.2.28 on 2026-02-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0002_organization_organizationmembership_and_more'),
        ('audit', '0002_alter_auditlog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finnovaapp.organization'),
        ),
    ]
