# Generated by Django 5.2.10 on 2026-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnova_autopilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilotprofile',
            name='auto_transfer_to_savings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autopilotprofile',
            name='fraud_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autopilotprofile',
            name='total_bills_auto_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
