# Generated by Django 4.2.28 on 2026-02-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finnovaapp', '0003_organization_segment'),
        ('finnova_autopilot', '0002_autopilotprofile_auto_transfer_to_savings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_alerts', to='finnovaapp.organization'),
        ),
        migrations.AddField(
            model_name='smartbill',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_bills', to='finnovaapp.organization'),
        ),
    ]
