# Generated by Django 5.2.10 on 2026-02-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finnova_autopilot', '0004_approval_requests_and_profile_controls'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='finnova_aut_user_id_77678f_idx',
            old_name='appr_user_status_created',
        ),
    ]
