# Generated by Django 5.2.10 on 2026-02-10 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_ai', '0001_initial'),
        ('finance', '0001_initial'),
        ('finnova_autopilot', '0001_initial'),
        ('payments_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('action_hint_template', models.CharField(blank=True, max_length=255, null=True)),
                ('default_severity', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('default_category', models.CharField(choices=[('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction'), ('BUDGET', 'Budget'), ('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment'), ('DEBT', 'Debt'), ('INCOME', 'Income'), ('BILL', 'Bill'), ('REMINDER', 'Reminder'), ('ALERT', 'Alert'), ('INSIGHT', 'Insight'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('PROMOTIONAL', 'Promotional'), ('UPDATE', 'Update')], default='SYSTEM', max_length=20)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('transaction_notifications', models.BooleanField(default=True)),
                ('budget_notifications', models.BooleanField(default=True)),
                ('savings_notifications', models.BooleanField(default=True)),
                ('investment_notifications', models.BooleanField(default=True)),
                ('debt_notifications', models.BooleanField(default=True)),
                ('income_notifications', models.BooleanField(default=True)),
                ('bill_notifications', models.BooleanField(default=True)),
                ('reminder_notifications', models.BooleanField(default=True)),
                ('alert_notifications', models.BooleanField(default=True)),
                ('insight_notifications', models.BooleanField(default=True)),
                ('security_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('promotional_notifications', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('daily_digest', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('monthly_report', models.BooleanField(default=True)),
                ('immediate_alerts', models.BooleanField(default=True)),
                ('batch_notifications', models.BooleanField(default=True)),
                ('batch_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('notification_language', models.CharField(default='en', max_length=10)),
                ('preferred_format', models.CharField(choices=[('TEXT', 'Text Only'), ('HTML', 'HTML Format'), ('RICH', 'Rich Format')], default='RICH', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction'), ('BUDGET', 'Budget'), ('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment'), ('DEBT', 'Debt'), ('INCOME', 'Income'), ('BILL', 'Bill'), ('REMINDER', 'Reminder'), ('ALERT', 'Alert'), ('INSIGHT', 'Insight'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('PROMOTIONAL', 'Promotional'), ('UPDATE', 'Update')], default='SYSTEM', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('delivery_method', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('ALL', 'All Channels')], default='IN_APP', max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_completed', models.BooleanField(default=False)),
                ('action_completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finnova_autopilot.alert')),
                ('related_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finnova_autopilot.smartbill')),
                ('related_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budget')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financialgoal')),
                ('related_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_ai.financialinsight')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_core.paymentintent')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_core.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['category', 'severity', 'created_at'], name='notificatio_categor_8b565a_idx'), models.Index(fields=['delivery_status', 'created_at'], name='notificatio_deliver_153ea5_idx')],
            },
        ),
    ]
