# Generated by Django 5.2.10 on 2026-02-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='agency_clie_organiz_9e1b5e_idx',
            old_name='agency_clie_organiza_6fda7b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='agency_invo_organiz_64fc26_idx',
            old_name='agency_invo_organiza_086d22_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='agency_invo_client__5accd7_idx',
            old_name='agency_invo_client__a4d4f9_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='agency_proj_organiz_b058c1_idx',
            old_name='agency_proj_organiza_098e0c_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='agency_proj_client__0a10e1_idx',
            old_name='agency_proj_client__693e7a_idx',
        ),
    ]
