# Generated by Django 4.2.28 on 2026-02-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments_core', '0007_add_payment_intent_idempotency'),
        ('agency', '0002_rename_agency_clie_organiza_6fda7b_idx_agency_clie_organiz_9e1b5e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_invoices', to='payments_core.paymentintent'),
        ),
    ]
